# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\"\x1d\n\x0eSendLogRequest\x12\x0b\n\x03log\x18\x01 \x01(\t\"\x0f\n\rEmptyResponse28\n\nLogService\x12*\n\x07SendLog\x12\x0f.SendLogRequest\x1a\x0e.EmptyResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENDLOGREQUEST._serialized_start=13
  _SENDLOGREQUEST._serialized_end=42
  _EMPTYRESPONSE._serialized_start=44
  _EMPTYRESPONSE._serialized_end=59
  _LOGSERVICE._serialized_start=61
  _LOGSERVICE._serialized_end=117
# @@protoc_insertion_point(module_scope)
